### PR TITLE
Enabled maxHttpHeaderSize customization

### PR DESCRIPTION
**Pull request by jiglesias-ntt**
### Requirements

* Filling out the template is required. Any pull request that does not include enough information to be reviewed in a timely manner may be closed at the maintainers' discretion.
* All new code requires tests to ensure against regressions
* Remember to set **idealista:develop** as base branch;

### Description of the Change

Add maxHttpHeaderSize option to be able to customize the value as nedeed

### Benefits

To be able to customize maxHttpHeaderSize value

### Possible Drawbacks

No drawbacks if i wrote it well. A default value is included in case you don't set any

### CODE REVIEW

**Comment by sorobon** [comment]
Thanks for taking the time to contribute @jiglesias-ntt.
Could you please update the changelog with the changes?.

**Comment by vicsufer** [comment]
Hi @jiglesias-ntt
Thanks for your contribution and sorry for the delay. in my opinion LGTM, can you update the changelog so we are good to go?

**Comment by jiglesias-ntt** [comment]
Hi @sorobon,
Could you tell me the section of the changelog where I should add the new entry?

Many thanks

**Comment by vicsufer** [comment]
Hi @jiglesias-ntt, it should be under the "Unreleased" section.

**Review by frantsao — APPROVED** [review]

**Review by vicsufer — APPROVED** [review]

**Review by sorobon — APPROVED** [review]

**Pull request merged**
